name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - '**.qmd'
      - '**.Rmd'
      - '**.yml'
      - 'envs/**'

env:
  # Set the base environment file path here - single source of truth
  BASE_ENV_FILE: 'envs/env.yml'
  # Use a different name for our primary environment to avoid conflicts
  PRIMARY_ENV_NAME: 'quarto-base'

defaults:
  run:
    shell: bash -l {0}
    
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore previous docs and freeze
        id: cache-docs
        uses: actions/cache@v3
        with:
          path: |
            ./docs
            ./_freeze
          key: quarto-${{ github.sha }}
          restore-keys: |
            quarto-

      - name: Verify base environment file
        run: |
          if [ ! -f "${{ env.BASE_ENV_FILE }}" ]; then
            echo "::error::Base environment file ${{ env.BASE_ENV_FILE }} does not exist!"
            exit 1
          fi
          echo "Using base environment file: ${{ env.BASE_ENV_FILE }}"

      - name: Set up base environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{ env.BASE_ENV_FILE }}
          environment-name: ${{ env.PRIMARY_ENV_NAME }}
          cache-environment: true

      - name: Activate base environment
        run: |
            micromamba --version
            micromamba activate ${{ env.PRIMARY_ENV_NAME }}

      - name: Install shinylive extension and packages
        run: |
          ./install_packages.sh

      - name: List quarto extensions
        run: quarto list extensions

      - name: Register base kernel
        run: |
          python -m ipykernel install --user --name "${{ env.PRIMARY_ENV_NAME }}" --display-name "Python (Base)"
          
      - name: Identify and create specialized environments
        run: |
          # Start with the base environment
          SPECIALIZED_ENVS=("${{ env.PRIMARY_ENV_NAME }}:${{ env.BASE_ENV_FILE }}")
          
          # Find all QMD files that have matching YML files
          echo "Searching for QMD files with matching YML files..."
          while IFS= read -r qmd_file; do
            # Get the directory and base name
            dir=$(dirname "$qmd_file")
            base_name=$(basename "$qmd_file" .qmd)
            
            # Check if a matching YML file exists
            yml_file="${dir}/${base_name}.yml"
            if [ -f "$yml_file" ]; then
              echo "Found matching YML for $qmd_file: $yml_file"
              
              # Add to the specialized environments list
              SPECIALIZED_ENVS+=("${base_name}:${yml_file}")
            fi
          done < <(find . -name "*.qmd" -not -path "*/\.*")
          
          # Print the discovered environments
          echo "Discovered the following specialized environments:"
          for env_spec in "${SPECIALIZED_ENVS[@]}"; do
            echo "  $env_spec"
          done
          
          # Create each specialized environment (skip the base environment which is already created)
          for env_spec in "${SPECIALIZED_ENVS[@]}"; do
            env_name="${env_spec%%:*}"
            env_file="${env_spec#*:}"
            
            # Skip the primary environment
            if [ "$env_name" = "${{ env.PRIMARY_ENV_NAME }}" ]; then
              echo "Skipping primary environment which is already created"
              continue
            fi
            
            echo "Creating environment $env_name from $env_file"
            # Start with the base environment
            micromamba create -n "$env_name" --file "${{ env.BASE_ENV_FILE }}"
            micromamba activate "$env_name"
            
            # Add the specialized packages
            micromamba install -y --file "$env_file"
            
            # Register the kernel with a predictable name
            python -m ipykernel install --user --name "$env_name" --display-name "Python ($env_name)"
            
            # Return to base environment
            micromamba activate ${{ env.PRIMARY_ENV_NAME }}
          done
          
          # List all available kernels for reference
          echo "Available Jupyter kernels:"
          jupyter kernelspec list
          
          # List all created environments
          echo "Created Micromamba environments:"
          micromamba env list

      - name: Render Quarto project
        run: |
          micromamba activate ${{ env.PRIMARY_ENV_NAME }}
          quarto render
      
          
      - name: Check docs directory
        run: |
          if [ ! -d "docs" ]; then
            echo "::error::Docs directory doesn't exist after rendering!"
            echo "Checking Quarto project configuration..."
            if [ -f "_quarto.yml" ]; then
              grep -i "output-dir\|output_dir" _quarto.yml || echo "No output-dir setting found"
            fi
            mkdir -p docs
            echo "<html><body>Build error - see logs</body></html>" > docs/index.html
          else
            echo "Docs directory contents:"
            ls -la docs/
          fi

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
