name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main

defaults:
  run:
    shell: bash -l {0}
    
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          cache-environment: true
          cache-downloads: true
          environment-name: web
          
      - name: Activate Env
        run: |
          micromamba activate web

#      - name: Upgrade pip
#        run: python -m pip install --upgrade pip

#      - name: Install shinylive
#        run: pip install shinylive

      - name: Install shinylive extension and package
        run: |
          ./install_packages.sh

#      - name: Install shinylive extension
#        run: |
#          quarto add --no-prompt quarto-ext/shinylive

#      - name: Install R-packages
#        run: |
#          Rscript install_packages.r
        
      - name: List quarto extensions
        run: quarto list extensions
          
      - name: Render
        run: quarto render
        
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
