name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main

defaults:
  run:
    shell: bash -l {0}
    
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          cache-environment: true
          cache-downloads: true
          environment-name: web
          
      - name: Activate Env
        run: |
          micromamba activate web

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

