name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - '**.qmd'
      - '**.Rmd'
      - '**.yml'
      - '**.yaml'
      - 'envs/**'
      - '.github/workflows/publish.yml'

defaults:
  run:
    shell: bash -l {0}
    
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to determine file changes

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Get changed files
        id: changed-files
        run: |
          echo "Finding QMD files to render..."
          
          # Check if we have a previous commit to compare against
          if [ -z "${{ github.event.before }}" ] || [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            # First run or full rebuild scenario - get all qmd files
            echo "First run or full rebuild detected, processing all QMD files"
            ALL_FILES=$(find . -name "*.qmd" -not -path "*/\.*" | sort)
            echo "changed_files=$ALL_FILES" >> $GITHUB_OUTPUT
          else
            # Get list of changed/added qmd files since last successful build
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.qmd$' || echo "")
            
            # If no changed files detected but docs directory doesn't exist, process all files
            if [ -z "$CHANGED_FILES" ] && [ ! -d "docs" ]; then
              echo "No docs directory found, processing all QMD files"
              ALL_FILES=$(find . -name "*.qmd" -not -path "*/\.*" | sort)
              echo "changed_files=$ALL_FILES" >> $GITHUB_OUTPUT
            else
              echo "Changed files: $CHANGED_FILES"
              echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Restore previous build
        id: cache-docs
        uses: actions/cache@v3
        with:
          path: ./docs
          key: quarto-docs-${{ github.sha }}
          restore-keys: |
            quarto-docs-

      - name: Create base conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: envs/env.yml
          cache-environment: true
          cache-downloads: true
          environment-name: base-env

      - name: Install ipykernel and nb_conda_kernels
        run: |
          micromamba activate base-env
          micromamba install -c conda-forge ipykernel nb_conda_kernels
          python -m ipykernel install --user --name base-env
          jupyter kernelspec list

      - name: Process QMD files with custom environments
        id: process-qmd
        if: steps.changed-files.outputs.changed_files != ''
        run: |
          micromamba activate base-env
          CHANGED_FILES="${{ steps.changed-files.outputs.changed_files }}"
          
          # Function to process a QMD file
          process_qmd() {
            local qmd_file=$1
            local dir=$(dirname "$qmd_file")
            local base_name=$(basename "$qmd_file" .qmd)
            local env_yaml="$dir/$base_name.yml"
            
            echo "Processing QMD: $qmd_file"
            
            # If custom environment file exists
            if [ -f "$env_yaml" ]; then
              echo "Found custom environment file: $env_yaml"
              
              # Create a custom environment for this QMD file
              env_name="${base_name}-env"
              echo "Creating environment: $env_name"
              
              # Create environment using base as starting point
              micromamba create -n $env_name --file envs/base.yml
              micromamba activate $env_name
              
              # Add additional packages from custom YAML
              micromamba install -y --file $env_yaml
              
              # Register the kernel
              python -m ipykernel install --user --name $env_name
              
              # Render the file with this environment
              echo "Rendering $qmd_file using environment $env_name"
              quarto render "$qmd_file"
              
              # Return to base environment for next file
              micromamba activate base-env
            else
              echo "No custom environment file found, using base environment"
              echo "Rendering $qmd_file using base environment"
              quarto render "$qmd_file"
            fi
          }
          
          # Process each changed file
          for file in $CHANGED_FILES; do
            process_qmd "$file"
          done

      - name: Verify output directory
        run: |
          if [ ! -d "docs" ]; then
            echo "Warning: docs directory still doesn't exist after rendering"
            
            # Look in _quarto.yml for output-dir setting
            if [ -f "_quarto.yml" ]; then
              echo "Checking _quarto.yml for output-dir setting:"
              grep -i "output-dir\|output_dir" _quarto.yml || echo "No output-dir setting found"
            fi
            
            # Create docs as fallback
            echo "Creating empty docs directory as fallback"
            mkdir -p docs
          else
            echo "docs directory exists, contains:"
            ls -la docs/
          fi

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
